import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import postcss from "postcss";
import tailwindcss from "tailwindcss";
import autoprefixer from "autoprefixer";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository
*/
`;

const prod = (process.argv[2] === "production");

// 1. CSS Build Function
async function buildCSS() {
    try {
        const css = fs.readFileSync("./src/styles.css", "utf8");
        const result = await postcss([
            tailwindcss,
            autoprefixer
        ]).process(css, { from: "./src/styles.css", to: "./styles.css" });
        
        fs.writeFileSync("./styles.css", result.css);
        console.log("[CSS] Build complete");
    } catch (e) {
        console.error("[CSS] Build failed:", e);
    }
}

// 2. JS Build Context
const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/closebrackets",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/comment",
		"@codemirror/fold",
		"@codemirror/gutter",
		"@codemirror/highlight",
		"@codemirror/history",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/matchbrackets",
		"@codemirror/panel",
		"@codemirror/rangeset",
		"@codemirror/rectangular-selection",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/stream-parser",
		"@codemirror/text",
		"@codemirror/tooltip",
		"@codemirror/view",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
    loader: {
        '.tsx': 'tsx',
        '.ts': 'ts'
    },
    define: {
        'process.env.NODE_ENV': prod ? '"production"' : '"development"',
        // IMPORTANT: In a real distribution, do NOT bake API keys here.
        // For personal use, you can uncomment below, but best practice is settings.
        // 'process.env.API_KEY': '"YOUR_KEY_HERE"' 
    }
});

// 3. Execution
if (prod) {
	await context.rebuild();
    await buildCSS();
	process.exit(0);
} else {
	await context.watch();
    // Watch CSS simply by rebuilding it on start. 
    // For true CSS watch, we'd add a separate watcher, but rebuilding on JS save is often enough for dev.
    await buildCSS();
    
    console.log("Watching for changes...");
    // Rudimentary CSS watcher
    fs.watch('./src/styles.css', () => buildCSS());
    fs.watch('./components', { recursive: true }, () => buildCSS());
    fs.watch('./tailwind.config.js', () => buildCSS());
}